#ifndef DEFINE_H
#define DEFINE_H

//IO DEFINE
#define LEAKSENSOR1 A0
#define LEAKSENSOR2 A1
#define LEAKSENSOR3 A2
#define VOLTSENSE A3
#define VIN A4
#define DIR 4
#define SENSORPWR 5
#define RELAY 6
#define LED 7

//SENSOR DEFINE
#define LEAKSENSORADDRESS 0x20
#define LEAKSENSORTYPE 0x10

#define SENSOR_CHANGE_ADDRESS 0x10
#define SENSOR_CHANGE_SCANRATE 0x11
#define SENSOR_CHANGE_FAULT 0x12
#define SENSOR_CHANGE_SENSOR_OPEN 0x13

#define SENSOR_SCAN_EN 0//Sensor Scan Enable
#define SENSOR_LED_CONTROL 1//LED Control
#define AUTO_SENSOR_RELAY_CONTROL 2 //Auto Relay Control - Default ON
#define SENSOR_RELAY 3 //Relay Control - Default OFF

#define SENSORSCANRATE 2
#define SENSORTESTTIMEMULTIPLYER 1000

#define SENSORHIGHFAULT 3
#define SENSORFAULT 2
#define SENSORWATERDETECT 1
#define SENSOROK 0
#define VOLT_AVG 10

#endif